### PR TITLE
fix: update sidebar scrollbar

### PR DESCRIPTION
**Pull request by sampoonachot**
## Description
- Increased opacity of white scrollbar and rounded corners to 10px

### Checklist
- [ ] New tests and/or benchmarks are included
- [ ] Documentation is changed or added

## Motivation and Context
- [ ] Bugfix
- [ ] New feature
- [ ] Dependency update
- [x] Misc

## Types of changes
- [ ] *Backport Needed*
- [ ] Patch (non-breaking change which fixes an issue)
- [x] Minor (non-breaking change which adds functionality)
- [ ] Major (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by sampoonachot** [comment]
Screen Shot 2019-09-27 at 11 00 54 AM

**Comment by lrlna** [comment]
looks good, @sampoonachot !

**Comment by sampoonachot** [comment]
> looks good, @sampoonachot !

@lrlna do I need to do an npm publish for this as well? not sure if that is needed for all PRs

**Comment by lrlna** [comment]
@sampoonachot yes, you need to publish for everything that you'd want in compass. 

So the flow is:
1. create a PR in applicable repo
2. once PR is merged, publish to npm
3. make a PR to compass updating the changed repo's version that you just published
4. get compass PR merged to master

sorry it's a bit long to get to compass 😅

**Pull request merged**
