### PR TITLE
COMPASS-3911 manage favorites after connecting

### PR DESCRIPTION
**Pull request by alenakhineika**
## Description

- Enable `save / edit / delete / color change` after saving connection to favorites
- Transform `FavoriteModal` to a pure component to reuse this component in other plugins
- Transform `FavoriteModal` to uncontrolled components to reuse this component in Redux based plugins
- Export `FavoriteModal` to reuse this component in other plugins eg `compass-sidebar`
- Ensure that all the time the same connection object is used to avoid favorite duplicates. One of the steps to do so is to use `lodash.merge` that recursively merges own and inherited enumerable string keyed properties of source objects into the destination object.

### Checklist
- [x] New tests and/or benchmarks are included
- [ ] Documentation is changed or added

## Motivation and Context

- [ ] Bugfix
- [ ] New feature
- [ ] Dependency update
- [x] Misc

## Types of changes

- [ ] *Backport Needed*
- [ ] Patch (non-breaking change which fixes an issue)
- [x] Minor (non-breaking change which adds functionality)
- [ ] Major (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by aherlihy** [comment]
Any reason why there are no tests edited or added for this PR?

(Also, a nitpick, but I think the format of the title needs to be be" COMPASS-#### - description" so that it can be picked up by the git hooks)

**Comment by alenakhineika** [comment]
@aherlihy these updated do not change `compass-connect` components behavior but they are necessary for `compass-sidebar` plugin. `compass-sidebar` will be using `FavoriteModal` that is being exported in this PR but the way as modal works stays the same. It affects modules interaction but not module itself. New `compass-sidebar` PR will be ready soon, but it needs the new version of `compass-connect` as a dependency.

**Comment by aherlihy** [comment]
You changed the favorites modal so that it takes different props, so this is a good opportunity to add a test that makes sure that that function is called. For example, you could change `shallow` to `mount` and use a spy to make sure the function is called. For saving favorites, it would look like:

```
const connection = {
      ...
      name: 'testname',
      color: 'testcolor'
};
let saveFavoriteSpy;
beforeEach(() => {
  saveFavoriteSpy = sinon.spy();
  component = mount(
       <FavoriteModal
          currentConnection={connection}
          saveFavorite={saveFavoriteSpy}
          ...
        />
      );
});
afterEach(() => {
  ...
  saveFavoriteSpy = null;
});
it('calls save favorite on click', () => {
  component.find('TextButton[dataTestId="create-favorite-button"]').simulate('click');
  expect(saveFavoriteSpy.calledWith('testname', 'testcolor')).to.equal(true);
});
```

**Comment by alenakhineika** [comment]
@aherlihy I have added more tests!

**Pull request merged**
