### PR TITLE
COMPASS-4150: handle password when switching views

### PR DESCRIPTION
**Pull request by alenakhineika**
## Description

Handle password while swithcing views:

- When switching to the connection form view do not display edit/hide buttons
- When a connection string is not editable when switching to the connection form view, use the real password to populate the input, do not use ***** value form the safe connection string.

### Checklist
- [x] New tests and/or benchmarks are included
- [ ] Documentation is changed or added

## Motivation and Context

- [x] Bugfix
- [ ] New feature
- [ ] Dependency update
- [ ] Misc

## Types of changes

- [ ] *Backport Needed*
- [x] Patch (non-breaking change which fixes an issue)
- [ ] Minor (non-breaking change which adds functionality)
- [ ] Major (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by alenakhineika** [comment]
@Anemy cool that you have noticed it! Fixed.

**Comment by Anemy** [comment]
Nice. I'm playing around with it a bit more and I think there's one more behavior we want to account for. It's a bit round about, but when a user has their connection string hidden, goes to connection fields individually, makes a few changes, then goes back to connection string and hits save changes, it saves the `*****` as the user's password, overwriting what they might have put as their password in the connection string changes.
connection password saving

**Comment by alenakhineika** [comment]
@Anemy updated!

**Comment by Anemy** [comment]
Ah I'm sorry - I found one more - like in the last one, when on the connection string view after making a change in the fields view, and `discard changes` is hit, it exposes the user's password in the url.

**Comment by alenakhineika** [comment]
@Anemy updated again!

**Pull request merged**
