### PR TITLE
connect-ui-tweaks: Cleaned up spacing between components

### PR DESCRIPTION
**Pull request by sampoonachot**
No ticket

## Description

Cleaned up padding and margin in connect form
Screen Shot 2019-10-30 at 12 46 12 PM
Screen Shot 2019-10-30 at 12 46 15 PM
Screen Shot 2019-10-30 at 12 47 23 PM

### Checklist
- [ ] New tests and/or benchmarks are included
- [ ] Documentation is changed or added

## Motivation and Context

- [ ] Bugfix
- [ ] New feature
- [ ] Dependency update
- [x] Misc

## Types of changes

- [ ] *Backport Needed*
- [x] Patch (non-breaking change which fixes an issue)
- [ ] Minor (non-breaking change which adds functionality)
- [ ] Major (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by fredtruman** [comment]
Hey @sampoonachot. Overall this is looking really nice! Some thoughts / questions mostly related to responsiveness:
- Wondering if we should have a max- & min-width for the connection card to prevent it from getting either too wide or too skinny. The min width should at the very least be wide enough so that the tabs can fit without poking into the Atlas CTA (see screenshot):
Screenshot 2019-10-30 16 04 32

- Likewise, while I think it's great we're making this responsive we may want to consider a max-width on the Atlas CTA column as a large screen will create a wide column of text (which is not great for readability) - and a min-width:
Screenshot 2019-10-30 16 08 38
Screenshot 2019-10-30 16 09 05

- One other way to approach this is to put max- & min-widths on the parent container which could simplify the css.
- If that doesn't work, another thing to consider is just allowing the Atlas CTA to bump beneath the connection card at smaller widths. Users won't see it anyways if its off the screen to the right and its likelier to scroll down than sideways.

**Comment by sampoonachot** [comment]
> Hey @sampoonachot. Overall this is looking really nice! Some thoughts / questions mostly related to responsiveness:
> 
> Wondering if we should have a max- & min-width for the connection card to prevent it from getting either too wide or too skinny. The min width should at the very least be wide enough so that the tabs can fit without poking into the Atlas CTA (see screenshot):

@fredtruman if we're setting a max-width on the containers, should the content be center aligned or left aligned?

responsive

**Comment by sampoonachot** [comment]
> Oh good question @sampoonachot - maybe left-aligned?

Oct-31-2019 14-25-46

**Comment by fredtruman** [comment]
Like it!

**Pull request merged**
